Permissionless Fishermen
pokt-network/pocket-network-protocol pull request #11
Opened 2022-09-01 03:59 UTC by DragonDmoney

This is the official spec PR following [ADR 001](https://github.com/pokt-network/pocket-network-protocol/issues/7). Let me know your thoughts and if there is anything you would like me to change!

CC: @luyzdeleon, @Olshansk, @andrewnguyen22

2022-09-03 22:44 UTC, Olshansk commented
@DragonDmoney I printed out section 3.3 and reviewed it by hand since it was a bit easier to do that way. There are some nits, some edits, some questions, etc... [PierreFishermanReview.pdf](https://github.com/pokt-network/pocket-network-protocol/files/9483503/PierreFishermanReview.pdf)


I think it's a good starting point, and a huge step in the right direction, but still needs a bit of work & discussion. For topics that you're unsure about, can you leave a `DISCUSS: <topic>` directly in markdown so we can use that as a starting point. In particular, I think it'd be good to have @andrewnguyen22 feedback on it too, so we can figure out what the minimum viable changes are that we can commit and iterate on in future iterations.

Also, two other things there missing are:
1. I think you should add Permisionless fisherman as a step in https://github.com/pokt-network/pocket-network-protocol/pull/11 since we likely won't have it straight off the bat.
2. Consider looking into additional attack vectors or dissenting opinions here: https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#5-attack-vectors.

For example, a madmen could potentially DOS a fisherman causing them to record that a ServiceNode was unavailable, causing more rewards to be distributed amongst the other fisherman. Note that this isn't a very well thought-through attack, but I think there are several others that should be explicitly considered.

2022-09-03 22:44 UTC, Olshansk requested changes
See comment above

2022-09-10 17:06 UTC, DragonDmoney commented
@Olshansk Here are some questions I had about your review:

[V1 Response Questions.pdf](https://github.com/pokt-network/pocket-network-protocol/files/9540996/V1.Response.Questions.pdf)

2023-05-16 22:23 UTC, Olshansk commented
@DragonDmoney Not now, but might ask you to pick up this work later this year ;)

2026-08-14 20:22 UTC, closed without merging