Update README.md
pokt-network/pocket-network-protocol pull request #13
Opened 2022-09-07 15:09 UTC by andrewnguyen22

# Objective
Create sequence diagrams and flow charts for the fisherman protocol.

# Origin Document

The fisherman protocol is the core of the V1 Pocket Network. As described in the [V1 Pocket Network Utility Fisherman Protocol Specification](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#33-fisherman-protocol), there are a lot of moving parts here.

# Issue

closes #12 

# Deliverables

[x] A sequence diagram showing the types of requests and flow of data throughout a fisherman's lifecycle using [mermaid flow charts](https://mermaid-js.github.io/mermaid/#/sequenceDiagram). Note that more than one may be necessary. For an example, see what we have in the [persistence module](https://github.com/pokt-network/pocket-network-protocol/tree/main/persistence#562-state-transition-sequence-diagram) architecture doc.

 [x] A flow chart showing which components and modules are involved in the fisherman protocol using [mermaid flow charts](https://mermaid-js.github.io/mermaid/#/flowchart)

 [x] Follow up tasks of things that need to be design and implemented (e.g. fast sync design, slow sync implementation, etc...)

Follow Up Tasks:
- Add glossary for *Variable* terminology e.g: FishermenSalaryPool
- Provide clarity on the AAT transfer protocol
- Further demonstrate non-null sample logic and interaction
- Follow up on the *Portal* interaction with the lifecycle

2022-09-07 15:12 UTC, Olshansk commented
@andrewnguyen22 Could you update the PR description to something more semantic like `[Utility] Adding Fisherman diagrams (Issue #12)`?

2022-10-05 17:37 UTC, andrewnguyen22 commented
@Olshansk bump as this affects https://github.com/pokt-network/pocket/issues/265 and https://github.com/pokt-network/pocket/issues/264

2022-10-05 20:00 UTC, Olshansk requested changes
Made a couple minor edits to the content + just making the diagrams easier to maintain.

I anticipate that we'll iterate, add an improve on these over time but I honestly think it already makes it 100x easier to read.

2022-10-08 12:47 UTC, Olshansk approved these changes
There's a small syntax error (introduced by me) where `graph LR` shows up twice, but LGTM otherwise.

2022-10-08 12:47 UTC, Olshansk commented on utility/README.md
> +graph LR
```suggestion
```

2022-10-08 12:51 UTC, merged